### PR TITLE
DO NOT MERGE!! Hotfix/1.0.3

### PR DESCRIPTION
**Pull request by ghost**
Please review @keiranmraine @AndyMenzies

### CODE REVIEW

**Comment by keiranmraine** [comment]
Will require an explicit note in the release notes and CHANGES.md to ensure we have communicated the behaviour change as this will cause problems for anyone using mate-paired data.

**Comment by keiranmraine** [comment]
Also the flag command line option will need to indicate that this will occur when filter includes proper-pair. @drjsanger

**Comment by AndyMenzies** [comment]
With the additions Keiran suggests it look good to me.

**Comment by ghost** [comment]
@keiranmraine @AndyMenzies Are these changes satisfactory?

**Comment by AndyMenzies** [comment]
The CHANGES.md and usage changes look good to me.

**Pull request closed without merging**
