### PR TITLE
Feature/ Add bam2bw -S/--scale-log10 to enable simple RPKM/CPM rescaling.

### PR DESCRIPTION
**Pull request by shouldsee**
bam2bw is blazing fast but unable to re-scaling is quite painful

### CODE REVIEW

**Comment by keiranmraine** [comment]
Can you clarify why you would want the raw data to be scaled resulting in different files for each mode?  Generally you would expect the consuming tool to scale the values.  For example in JBrowse:

Screen Shot 2020-03-23 at 16 51 05

I believe IGV has a similar option.

I'm not saying we will block this, but I'm wanting to ensure this is appropriate.

**Comment by shouldsee** [comment]
> Can you clarify why you would want the raw data to be scaled resulting in different files for each mode? Generally you would expect the consuming tool to scale the values. For example in JBrowse:
> 
> Screen Shot 2020-03-23 at 16 51 05
> 
> I believe IGV has a similar option.
> 
> I'm not saying we will block this, but I'm wanting to ensure this is appropriate.

Dear keiran, sorry for not being clear. The `--scale-log10` option triggers a global multiplier `f(x) = 10^(scale_log10) * x` instead of a global log-transfomation `f(x) = log10(x)`. A global multiplication is useful for normalising the track so that library of different sequencing depth can be compared. e.g. say for the same reference bam1 has 2M tags whereas bam2 has 10M tags, you would expect bam2 to display a value 5 times larger, and this discrepancy can be taken out by dividing the total tag count. Aka `CPM(pos) = Coverage(pos)/library_total_count`.  Supplying an argument for multiplier allow user to tailor the normalisation to their need by computing a suitable normalisation factor.

Normalisation removes information about library size, which in functional genomics is often deemed as unimportant after QC is done.

Let me know if anything isn't clear.

Feng

**Comment by keiranmraine** [comment]
@davidrajones are you able to review this, reasoning for addition seems sound to me.

@shouldsee can you provide test input/ouput data for us to add to our internal CI system (we have a large scale CI internally where we run genome scale testing).

**Comment by shouldsee** [comment]
I have added a test to the following files. Let me know if this is not sufficient.

`c/c_tests/test_2bam2bw.sh`
https://github.com/cancerit/cgpBigWig/pull/36/commits/b024993a7a26204de46060fe8dd8ea960c35d062#diff-38d8934122a813025f2ea5ff3c791ca1R214
`test_data/test_bw_out_logs1_expected.txt`
https://github.com/cancerit/cgpBigWig/commit/b024993a7a26204de46060fe8dd8ea960c35d062#diff-9fbbf3abeb2b5aad293d4c9cc258020eR1

**Comment by davidrajones** [comment]
@shouldsee Released as https://github.com/cancerit/cgpBigWig/releases/tag/1.2.0

**Comment by shouldsee** [comment]
That's great! Thanks for the timely response!

**Pull request merged**
