### PR TITLE
Feature/Add Dockerfile and improve README and INSTALL docs

### PR DESCRIPTION
**Pull request by jsmedmar**
This PR is up to date with #18. I'm proposing a simple `Dockerfile` which comes in sync with https://github.com/cancerit/PCAP-core/pull/13, https://github.com/cancerit/cgpVcf/pull/23 and https://github.com/cancerit/cgpPindel/pull/57. 

* 🚀 **Features**
    - Add `Dockerfiles` with the minimum requirements necessary to build the programs.
    - Add `.dockerignore` with `C` and `Perl` ignored files.
* 📝 **Documentation changes**
    - Add `CONTRIBUTING` guidelines with `Creating a release` section.
    - Add installation documentation for ubuntu 16.04 as per #17, whilst fixing any formatting issue.
    - Add table of contents section to `README`.
* 🎨 **Style changes**
    - Add table to *programs* section.
    - Format tables in `Markdown`, happy to revert this (for me is ok since editor fixes tables formatting on save).

Please see how [README] and [INSTALL] render.

# PCAP-core

I also created this PR: https://github.com/cancerit/PCAP-core/pull/13. I think it make sense to build the docker files on top of each other (PCAP-core imports from cgpBigWig). As a result, the PCAP-core Docker file is very simple and I think that makes it easier to maintain, [check it out](https://github.com/jsmedmar/PCAP-core/blob/feature/add-dockerfile/Dockerfile). The PCAP-core PR proposes the same changes in docs.

# cgpVcf

Same with  with https://github.com/cancerit/cgpVcf/pull/23. `cgpVcf` Dockerfile imports from `PCAP-core` so that projects that depend on `cgpVcf` will have both `cgpBigWig` and `PCAP-core` already set. However, its important to note that `PCAP-core` is not a cgpVCF dependency. cgpVcf image without `PCAP-core` is 585MB, with `PCAP-core` is 871MB.

`cgpVcf` system dependencies for ubuntu 16 are:

    curl              | Missing in `pcap-core`
    build-essential
    libgnutls-dev

# cgpPindel

https://github.com/cancerit/cgpPindel/pull/57: Imports from cgpVcf container which includes cgpBigWig, PCAP-core and cgpVcf. cgpPindel system dependencies are satisfied with a successful install of cgpVcf. As such `cgpPindel`  [Dockerfile](https://github.com/jsmedmar/cgpPindel/blob/13cbf20663703914bd46400b2dbe06b255ca97ba/Dockerfile) is just a few lines.

# Other Considerations

As you noticed, each Dockerfile builds on top of each other in the dependency chain:

    cgp-bigwig
    └── pcap-core
        └── cgp-vcf
            ├── ...
            └── cgp-pindel

It would be great to have a **versioned** `cancerit/cgpDocker` repository so that other projects that are not in this dependency chain could benefit from boiler plate configurations.

    cgp-docker
    ├── cgp-bigwig
    │   └── pcap-core
    │       └── cgp-vcf
    │           ├── ...
    │           └── cgp-pindel
    ├── vaf-correct
    └── vagrent

I would recommend this as the `cgpDocker/Dockerfile`:

```
# Use ubuntu 16 across all the stack.
FROM ubuntu:16.04

# Set maintainer labels.
LABEL maintainer Keiran M. Raine <kr2@sanger.ac.uk>
LABEL maintainer ...

# Install all dependencies in OPT.
ENV OPT /opt/bundle

# Export bundle bin and lib to PATH and PERL5LIB.
ENV PATH $OPT/bin:$PATH
ENV PERL5LIB $OPT/lib/perl5:$PERL5LIB

# Install package and dependencies.
RUN \
    # Make OPT dirs.
    mkdir -p $OPT/bin $OPT/etc $OPT/lib $OPT/share && \
    \
    # Install basic system dependencies.
    apt-get -yqq update --fix-missing && \
    apt-get -yqq install \
        build-essential \
        locales \
    && \
    apt-get clean && \
    \
    # Configure default locale, see below.
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && \
    locale-gen en_US.utf8 && \
    /usr/sbin/update-locale LANG=en_US.UTF-8

# For best interoperability, it should be UTF-8.
# Some information about it here:
# https://github.com/rocker-org/rocker/issues/19
# http://jaredmarkell.com/docker-and-locales/
# http://click.pocoo.org/5/python3/
# https://crosbymichael.com/dockerfile-best-practices-take-2.html
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8

# Set volume to data as per:
# https://github.com/BD2KGenomics/cgl-docker-lib
VOLUME /data
WORKDIR /data
```

[README]: https://github.com/jsmedmar/cgpBigWig/blob/install-docs-improvement/README.md
[INSTALL]: https://github.com/jsmedmar/cgpBigWig/blob/install-docs-improvement/INSTALL.md

### CODE REVIEW

**Comment by jsmedmar** [comment]
Hey I noticed @drjsanger and myself were working in the same stuff during the weekend. This PR has conflicts with #21 😆

**Comment by keiranmraine** [comment]
Hi,
 
Unfortunately, we already have docker images ready for standard use of our systems.  We make these specifically for use within the Dockstore.org framework so there are some specific requirements for how they are constructed.  Additionally, we always keep them separate from the core codebases so that pre-release tags aren't auto built as available images.
 
Currently we have 'fat' tools that incorporate complete workflows with a CWL descriptor so they can be easily configured by json files.
 
See:
 
* [dockstore-cgpmap](https://github.com/cancerit/dockstore-cgpmap)
  * PCAP-core (and deps)
* [dockstore-cgpwxs](https://github.com/cancerit/dockstore-cgpwxs)
  * Adds CaVEMan, cgpPindel and VAGrENT
* [dockstore-cgpwgs](https://github.com/cancerit/dockstore-cgpwgs)
  * Adds BRASS, ascatNgs genotype and gender checking.
 
These have been used extensively in the PanProstate project.
 
We've had this for the bundled tools under dockstore.org framework for about a year and are currently doing a large overhaul using build stages to produce far smaller images and improve usability for people running them under Singularity.
 
dockstore-cgpwgs has a carefully constructed script to ensure minimal wasted resource when run on a large instance (e.g. 24cpu).
 
Sorry about the lack of docs pointing to the docker versions, will ensure these are added in any upcoming releases (most are being updated this month).

**Comment by jsmedmar** [comment]
Closing then.

**Comment by jsmedmar** [comment]
Thanks for your answer, sorry I couldn't reply sooner. Thank you for pointing to these resources. Wondering if cgp-wxs can be used for Targeted Sequencing Data?

I see why you don't want to support multiple dockerfiles across your systems. I just thought It could be nice to be able to use your tools independently. But will give a try to the `dockstore-*` repos for sure!

Looking forward to the singularity support.

**Comment by keiranmraine** [comment]
@jsmedmar , yes cgpwxs can be used for targeted data, you would want to either change the applied filter rules or just ignore them in the final filtered VCF.

**Pull request closed without merging**
